# Static config for eth0
auto eth0
iface eth0 inet static
    address 192.168.10.101
    netmask 255.255.255.0
    gateway 192.168.10.1
    up echo nameserver 192.168.10.1 > /etc/resolv.conf
    
    # จัดข้อความให้อยู่กึ่งกลางหน้าจอแบบแนวนอนและแนวตั้ง
  post-up ( sleep 5 && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && mkdir -p /var/www/html && echo '<!DOCTYPE html><html><head><style>body{display:flex;justify-content:center;align-items:center;height:100vh;margin:0;font-family:sans-serif;background-color:#f4f4f9;}</style></head><body><h1>Hello! from server2</h1></body></html>' > /var/www/html/index.html && cd /var/www/html && python3 -m http.server 80 ) &
