auto lo
iface lo inet loopback

auto eth0 eth1 eth2 eth3 eth4 eth5
iface eth0 inet manual
iface eth1 inet manual
iface eth2 inet manual
iface eth3 inet manual
iface eth4 inet manual
iface eth5 inet manual

auto br0
iface br0 inet manual
    pre-up ovs-vsctl del-br br0 2>/dev/null || true
    pre-up ovs-vsctl del-br br1 2>/dev/null || true
    
    pre-up ovs-vsctl add-br br0
    pre-up ovs-vsctl set bridge br0 stp_enable=true
    
    # Access Port: webterm-1 (eth1)
    pre-up ovs-vsctl add-port br0 eth1 tag=20
    pre-up ovs-vsctl set port eth1 other_config:stp-enable=false
    pre-up ovs-vsctl set port eth1 other_config:stp-bpdu-guard=true
    
    # Trunk Ports (ห้ามเปิด BPDU Guard)
    pre-up ovs-vsctl add-port br0 eth0 trunks=10,20,30
    pre-up ovs-vsctl add-port br0 eth2 trunks=10,20,30
    pre-up ovs-vsctl add-port br0 eth3 trunks=10,20,30
    pre-up ovs-vsctl add-port br0 eth4 trunks=10,20,30
    pre-up ovs-vsctl add-port br0 eth5 trunks=10,20,30
