# 1. ประกาศ Loopback
auto lo
iface lo inet loopback

# 2. ตั้งค่า Bridge br0 แบบ Native OVS (ตั้ง Priority เป็น 0x1000 / 4096)
allow-ovs br0
iface br0 inet manual
    ovs_type OVSBridge
    ovs_ports eth0 lacp-bond eth2 eth3 eth4
    ovs_extra set bridge br0 stp_enable=true -- set bridge br0 other_config:stp-priority=0x1000

# 3. ตั้งค่า LACP Bond (eth1 + eth5) ต่อหา OVS2
allow-br0 lacp-bond
iface lacp-bond inet manual
    ovs_bridge br0
    ovs_type OVSBond
    ovs_bonds eth1 eth5
    ovs_options lacp=active bond_mode=balance-tcp

# 4. ประกาศ Ports สมาชิกของ br0
allow-br0 eth0
iface eth0 inet manual
    ovs_bridge br0
    ovs_type OVSPort

allow-br0 eth2
iface eth2 inet manual
    ovs_bridge br0
    ovs_type OVSPort

allow-br0 eth3
iface eth3 inet manual
    ovs_bridge br0
    ovs_type OVSPort

allow-br0 eth4
iface eth4 inet manual
    ovs_bridge br0
    ovs_type OVSPort
